// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/layout/banner/index.vue')['default']
    CoverPlay: typeof import('./src/components/common/CoverPlay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/index.vue')['default']
    Header: typeof import('./src/components/layout/header/index.vue')['default']
    IconPark: typeof import('./src/components/common/iconPark/index.vue')['default']
    Menu: typeof import('./src/components/layout/menu/index.vue')['default']
    MenuList: typeof import('./src/components/layout/menu/menuList.vue')['default']
    MoreText: typeof import('./src/components/common/moreText/index.vue')['default']
    PlayerActions: typeof import('./src/components/layout/footer/playerActions.vue')['default']
    PlayerBar: typeof import('./src/components/layout/footer/playerBar.vue')['default']
    PlayerController: typeof import('./src/components/layout/footer/playerController.vue')['default']
    PlayerSong: typeof import('./src/components/layout/footer/playerSong.vue')['default']
    PlayerVolunmeSmallBar: typeof import('./src/components/layout/footer/playerVolunmeSmallBar.vue')['default']
    PlayList: typeof import('./src/components/common/playList/index.vue')['default']
    PlayListSongItem: typeof import('./src/components/common/playList/playListSongItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/layout/header/searchInput.vue')['default']
    SongItem: typeof import('./src/components/common/songItem/index.vue')['default']
    SuggestSearch: typeof import('./src/components/layout/header/suggestSearch.vue')['default']
    Title: typeof import('./src/components/common/title/index.vue')['default']
    UserInfo: typeof import('./src/components/layout/header/userInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
